### ISSUE TITLE
Code review request

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kdart/pycopia#9]
```
Purpose of code changes on this branch:
Add a terminal mode interface for database editing using the urwid toolkit.


When reviewing my code changes, please focus on:
Usage of urwid widgets, proper subclassing, and signal usage. Particularly, is 
it necessary to unregister signals when an object is no longer needed (goes out 
of scope)?


After the review, I'll merge this branch into:
/trunk

```

Original issue reported on code.google.com by `keith.d...@gmail.com` on 8 Nov 2012 at 4:51

**Comment by pradyunsg** [comment]
I'm willling...

**Comment by kdart** [comment]
Hello... thanks for being willing. But this request seems to be an artifact of the transfer of code from Google code hosting to github.  The code is already in there, but some aspects of urwid I had to guess at, and IIRC, this review was for the urwid author to take a look at it.
